import type { Abstract, AbstractComment } from './types'

export const mockAbstracts: Abstract[] = [
  {
    id: 1,
    subThemeCategory: 'THEME_1',
    title: 'Innovative Leadership Models in African Medical Education',
    authorInformation: 'Dr. Jane Smith, PhD, jane.smith@university.edu, University of Nairobi\nDr. John Doe, MD, john.doe@hospital.org, Kenyatta National Hospital',
    presentationType: 'Oral',
    presenterFullName: 'Dr. Jane Smith',
    presenterEmail: 'jane.smith@university.edu',
    presenterPhone: '+254712345678',
    presenterInstitution: 'University of Nairobi',
    presenterCountry: 'Kenya',
    deanContact: 'Dean Prof. Mary Johnson, dean@university.edu, +254711111111',
    abstractBody: '<p><strong>Background:</strong> Leadership in African medical education requires culturally adapted models that address unique challenges in resource-limited settings.</p><p><strong>Methods:</strong> We conducted a mixed-methods study involving 150 medical educators across 10 African countries to identify effective leadership practices.</p><p><strong>Findings:</strong> Collaborative leadership models that emphasize community engagement and local ownership showed 40% better outcomes in program sustainability.</p><p><strong>Discussion:</strong> These findings suggest that African-centered leadership approaches can significantly improve medical education outcomes.</p>',
    status: 'pending',
    submittedBy: 'user-1',
    createdAt: '2024-01-28T10:30:00Z',
    updatedAt: '2024-01-28T10:30:00Z',
  },
  {
    id: 2,
    subThemeCategory: 'THEME_2',
    title: 'AI-Powered Simulation for Medical Training',
    authorInformation: 'Dr. Robert Chen, PhD, robert.chen@tech.edu, University of Cape Town',
    presentationType: 'Oral',
    presenterFullName: 'Dr. Robert Chen',
    presenterEmail: 'robert.chen@tech.edu',
    presenterPhone: '+27123456789',
    presenterInstitution: 'University of Cape Town',
    presenterCountry: 'South Africa',
    abstractBody: '<p><strong>Background:</strong> Artificial intelligence offers unprecedented opportunities to enhance medical simulation training.</p><p><strong>Methods:</strong> We developed an AI-powered simulation platform tested with 200 medical students over 6 months.</p><p><strong>Findings:</strong> Students using AI-enhanced simulations showed 35% improvement in diagnostic accuracy compared to traditional methods.</p><p><strong>Discussion:</strong> AI integration in medical education can bridge the gap between theoretical knowledge and practical skills.</p>',
    status: 'approved',
    submittedBy: 'user-2',
    createdAt: '2024-01-27T14:20:00Z',
    updatedAt: '2024-01-29T09:15:00Z',
    reviewedBy: 'reviewer-1',
    reviewedAt: '2024-01-29T09:15:00Z',
  },
  {
    id: 3,
    subThemeCategory: 'THEME_3',
    title: 'Virtual Reality Clinical Skills Training',
    authorInformation: 'Dr. Amina Hassan, MD, amina.hassan@medical.edu, Makerere University',
    presentationType: 'Poster',
    presenterFullName: 'Dr. Amina Hassan',
    presenterEmail: 'amina.hassan@medical.edu',
    presenterPhone: '+256701234567',
    presenterInstitution: 'Makerere University',
    presenterCountry: 'Uganda',
    abstractBody: '<p><strong>Background:</strong> VR technology provides immersive learning experiences for clinical skills development.</p><p><strong>Methods:</strong> Pilot study with 80 nursing students using VR for emergency response training.</p><p><strong>Findings:</strong> VR training improved confidence levels by 45% and reduced errors in real scenarios by 30%.</p><p><strong>Discussion:</strong> VR offers scalable solutions for clinical training in resource-constrained environments.</p>',
    status: 'more_info_requested',
    submittedBy: 'user-3',
    createdAt: '2024-01-26T11:00:00Z',
    updatedAt: '2024-01-28T16:30:00Z',
    reviewedBy: 'reviewer-1',
    reviewedAt: '2024-01-28T16:30:00Z',
  },
  {
    id: 4,
    subThemeCategory: 'THEME_4',
    title: 'Community-University Partnerships for Rural Health',
    authorInformation: 'Dr. David Omondi, MPH, david.omondi@health.gov, Ministry of Health Kenya',
    presentationType: 'Workshop',
    presenterFullName: 'Dr. David Omondi',
    presenterEmail: 'david.omondi@health.gov',
    presenterPhone: '+254722334455',
    presenterInstitution: 'Ministry of Health Kenya',
    presenterCountry: 'Kenya',
    abstractBody: '<p><strong>Background:</strong> Strengthening rural health systems requires collaborative partnerships between universities and communities.</p><p><strong>Methods:</strong> Established 5 community-university partnerships in rural Kenya over 2 years.</p><p><strong>Findings:</strong> Partnerships led to 60% increase in healthcare worker retention and improved health outcomes.</p><p><strong>Discussion:</strong> Sustainable partnerships are key to addressing health workforce challenges in rural areas.</p>',
    status: 'rejected',
    submittedBy: 'user-4',
    createdAt: '2024-01-25T09:45:00Z',
    updatedAt: '2024-01-27T13:20:00Z',
    reviewedBy: 'reviewer-2',
    reviewedAt: '2024-01-27T13:20:00Z',
  },
  {
    id: 5,
    subThemeCategory: 'THEME_5',
    title: 'Gender-Sensitive Maternal Health Education',
    authorInformation: 'Dr. Sarah Mwangi, MD, sarah.mwangi@hospital.org, Aga Khan University Hospital',
    presentationType: 'Oral',
    presenterFullName: 'Dr. Sarah Mwangi',
    presenterEmail: 'sarah.mwangi@hospital.org',
    presenterPhone: '+254733445566',
    presenterInstitution: 'Aga Khan University Hospital',
    presenterCountry: 'Kenya',
    abstractBody: '<p><strong>Background:</strong> Gender considerations are crucial in maternal and child health education programs.</p><p><strong>Methods:</strong> Implemented gender-sensitive curriculum for 300 healthcare workers.</p><p><strong>Findings:</strong> Gender-sensitive training improved patient satisfaction by 50% and reduced maternal complications.</p><p><strong>Discussion:</strong> Integrating gender perspectives in MNCH education enhances healthcare delivery.</p>',
    status: 'pending',
    submittedBy: 'user-5',
    createdAt: '2024-01-29T08:00:00Z',
    updatedAt: '2024-01-29T08:00:00Z',
  },
  {
    id: 6,
    subThemeCategory: 'THEME_6',
    title: 'Competency-Based Assessment in Medical Education',
    authorInformation: 'Prof. Michael Akinyi, PhD, michael.akinyi@university.ac.tz, Muhimbili University',
    presentationType: 'Oral',
    presenterFullName: 'Prof. Michael Akinyi',
    presenterEmail: 'michael.akinyi@university.ac.tz',
    presenterPhone: '+255789123456',
    presenterInstitution: 'Muhimbili University of Health and Allied Sciences',
    presenterCountry: 'Tanzania',
    abstractBody: '<p><strong>Background:</strong> Competency-based assessment ensures medical graduates meet required standards.</p><p><strong>Methods:</strong> Developed and validated competency assessment framework across 4 medical schools.</p><p><strong>Findings:</strong> Framework improved assessment reliability by 55% and better predicted clinical performance.</p><p><strong>Discussion:</strong> Standardized competency assessment enhances quality assurance in medical education.</p>',
    status: 'approved',
    submittedBy: 'user-6',
    createdAt: '2024-01-24T15:30:00Z',
    updatedAt: '2024-01-26T10:45:00Z',
    reviewedBy: 'reviewer-1',
    reviewedAt: '2024-01-26T10:45:00Z',
  },
]

export const mockComments: { [abstractId: number]: AbstractComment[] } = {
  1: [
    {
      id: 1,
      abstractId: 1,
      submittedBy: 'reviewer-1',
      comment: 'This is a very interesting study. Could you provide more details about the methodology used to select the 10 African countries?',
      createdAt: '2024-01-28T14:30:00Z',
      updatedAt: '2024-01-28T14:30:00Z',
    },
    {
      id: 2,
      abstractId: 1,
      submittedBy: 'reviewer-2',
      comment: 'The 40% improvement is impressive. Have you considered submitting this for an oral presentation?',
      createdAt: '2024-01-29T09:00:00Z',
      updatedAt: '2024-01-29T09:00:00Z',
    },
  ],
  2: [
    {
      id: 3,
      abstractId: 2,
      submittedBy: 'reviewer-1',
      comment: 'Excellent work! The AI integration is well-thought-out. Approved for oral presentation.',
      createdAt: '2024-01-29T09:15:00Z',
      updatedAt: '2024-01-29T09:15:00Z',
    },
  ],
  3: [
    {
      id: 4,
      abstractId: 3,
      submittedBy: 'reviewer-1',
      comment: 'Please provide more information about the VR equipment used and cost analysis for implementation.',
      createdAt: '2024-01-28T16:30:00Z',
      updatedAt: '2024-01-28T16:30:00Z',
    },
  ],
  4: [
    {
      id: 5,
      abstractId: 4,
      submittedBy: 'reviewer-2',
      comment: 'The methodology section needs more detail. The sample size appears too small for the conclusions drawn.',
      createdAt: '2024-01-27T13:20:00Z',
      updatedAt: '2024-01-27T13:20:00Z',
    },
  ],
  5: [],
  6: [
    {
      id: 6,
      abstractId: 6,
      submittedBy: 'reviewer-1',
      comment: 'Outstanding research with significant implications for medical education. Strongly recommend for oral presentation.',
      createdAt: '2024-01-26T10:45:00Z',
      updatedAt: '2024-01-26T10:45:00Z',
    },
  ],
}
