import type { Abstract, Comment } from './types'

export const mockAbstracts: Abstract[] = [
  {
    id: 'abstract-1',
    subThemeCategory: 'Leadership, Governance, and African Ownership in Health Professions Education',
    title: 'Innovative Leadership Models in African Medical Education',
    authorInformation: 'Dr. Jane Smith, PhD, jane.smith@university.edu, University of Nairobi\nDr. John Doe, MD, john.doe@hospital.org, Kenyatta National Hospital',
    presentationType: 'Oral Presentation',
    presenterFullName: 'Dr. Jane Smith',
    presenterEmail: 'jane.smith@university.edu',
    presenterPhone: '+254712345678',
    presenterInstitution: 'University of Nairobi',
    presenterCountry: 'Kenya',
    deanContact: 'Dean Prof. Mary Johnson, dean@university.edu, +254711111111',
    abstractBody: '<p><strong>Background:</strong> Leadership in African medical education requires culturally adapted models that address unique challenges in resource-limited settings.</p><p><strong>Methods:</strong> We conducted a mixed-methods study involving 150 medical educators across 10 African countries to identify effective leadership practices.</p><p><strong>Findings:</strong> Collaborative leadership models that emphasize community engagement and local ownership showed 40% better outcomes in program sustainability.</p><p><strong>Discussion:</strong> These findings suggest that African-centered leadership approaches can significantly improve medical education outcomes.</p>',
    status: 'pending',
    submittedBy: 'user-1',
    submittedAt: '2024-01-28T10:30:00Z',
  },
  {
    id: 'abstract-2',
    subThemeCategory: 'Transformative Technologies, AI, and Innovation in Medical Education',
    title: 'AI-Powered Simulation for Medical Training',
    authorInformation: 'Dr. Robert Chen, PhD, robert.chen@tech.edu, University of Cape Town',
    presentationType: 'Oral Presentation',
    presenterFullName: 'Dr. Robert Chen',
    presenterEmail: 'robert.chen@tech.edu',
    presenterPhone: '+27123456789',
    presenterInstitution: 'University of Cape Town',
    presenterCountry: 'South Africa',
    abstractBody: '<p><strong>Background:</strong> Artificial intelligence offers unprecedented opportunities to enhance medical simulation training.</p><p><strong>Methods:</strong> We developed an AI-powered simulation platform tested with 200 medical students over 6 months.</p><p><strong>Findings:</strong> Students using AI-enhanced simulations showed 35% improvement in diagnostic accuracy compared to traditional methods.</p><p><strong>Discussion:</strong> AI integration in medical education can bridge the gap between theoretical knowledge and practical skills.</p>',
    status: 'approved',
    submittedBy: 'user-2',
    submittedAt: '2024-01-27T14:20:00Z',
    reviewedBy: 'reviewer-1',
    reviewedAt: '2024-01-29T09:15:00Z',
  },
  {
    id: 'abstract-3',
    subThemeCategory: 'Simulation-Based Education and Experiential Learning',
    title: 'Virtual Reality Clinical Skills Training',
    authorInformation: 'Dr. Amina Hassan, MD, amina.hassan@medical.edu, Makerere University',
    presentationType: 'Poster Presentation',
    presenterFullName: 'Dr. Amina Hassan',
    presenterEmail: 'amina.hassan@medical.edu',
    presenterPhone: '+256701234567',
    presenterInstitution: 'Makerere University',
    presenterCountry: 'Uganda',
    abstractBody: '<p><strong>Background:</strong> VR technology provides immersive learning experiences for clinical skills development.</p><p><strong>Methods:</strong> Pilot study with 80 nursing students using VR for emergency response training.</p><p><strong>Findings:</strong> VR training improved confidence levels by 45% and reduced errors in real scenarios by 30%.</p><p><strong>Discussion:</strong> VR offers scalable solutions for clinical training in resource-constrained environments.</p>',
    status: 'info_requested',
    submittedBy: 'user-3',
    submittedAt: '2024-01-26T11:00:00Z',
    reviewedBy: 'reviewer-1',
    reviewedAt: '2024-01-28T16:30:00Z',
  },
  {
    id: 'abstract-4',
    subThemeCategory: 'Partnerships for Health Workforce and Systems Strengthening',
    title: 'Community-University Partnerships for Rural Health',
    authorInformation: 'Dr. David Omondi, MPH, david.omondi@health.gov, Ministry of Health Kenya',
    presentationType: 'Workshop',
    presenterFullName: 'Dr. David Omondi',
    presenterEmail: 'david.omondi@health.gov',
    presenterPhone: '+254722334455',
    presenterInstitution: 'Ministry of Health Kenya',
    presenterCountry: 'Kenya',
    abstractBody: '<p><strong>Background:</strong> Strengthening rural health systems requires collaborative partnerships between universities and communities.</p><p><strong>Methods:</strong> Established 5 community-university partnerships in rural Kenya over 2 years.</p><p><strong>Findings:</strong> Partnerships led to 60% increase in healthcare worker retention and improved health outcomes.</p><p><strong>Discussion:</strong> Sustainable partnerships are key to addressing health workforce challenges in rural areas.</p>',
    status: 'rejected',
    submittedBy: 'user-4',
    submittedAt: '2024-01-25T09:45:00Z',
    reviewedBy: 'reviewer-2',
    reviewedAt: '2024-01-27T13:20:00Z',
  },
  {
    id: 'abstract-5',
    subThemeCategory: 'Education for Impact: MNCH, Gender, and Sexual & Reproductive Health',
    title: 'Gender-Sensitive Maternal Health Education',
    authorInformation: 'Dr. Sarah Mwangi, MD, sarah.mwangi@hospital.org, Aga Khan University Hospital',
    presentationType: 'Oral Presentation',
    presenterFullName: 'Dr. Sarah Mwangi',
    presenterEmail: 'sarah.mwangi@hospital.org',
    presenterPhone: '+254733445566',
    presenterInstitution: 'Aga Khan University Hospital',
    presenterCountry: 'Kenya',
    abstractBody: '<p><strong>Background:</strong> Gender considerations are crucial in maternal and child health education programs.</p><p><strong>Methods:</strong> Implemented gender-sensitive curriculum for 300 healthcare workers.</p><p><strong>Findings:</strong> Gender-sensitive training improved patient satisfaction by 50% and reduced maternal complications.</p><p><strong>Discussion:</strong> Integrating gender perspectives in MNCH education enhances healthcare delivery.</p>',
    status: 'pending',
    submittedBy: 'user-5',
    submittedAt: '2024-01-29T08:00:00Z',
  },
  {
    id: 'abstract-6',
    subThemeCategory: 'Learners at the Center: Assessment, Accreditation, Research, and Implementation for Change',
    title: 'Competency-Based Assessment in Medical Education',
    authorInformation: 'Prof. Michael Akinyi, PhD, michael.akinyi@university.ac.tz, Muhimbili University',
    presentationType: 'Oral Presentation',
    presenterFullName: 'Prof. Michael Akinyi',
    presenterEmail: 'michael.akinyi@university.ac.tz',
    presenterPhone: '+255789123456',
    presenterInstitution: 'Muhimbili University of Health and Allied Sciences',
    presenterCountry: 'Tanzania',
    abstractBody: '<p><strong>Background:</strong> Competency-based assessment ensures medical graduates meet required standards.</p><p><strong>Methods:</strong> Developed and validated competency assessment framework across 4 medical schools.</p><p><strong>Findings:</strong> Framework improved assessment reliability by 55% and better predicted clinical performance.</p><p><strong>Discussion:</strong> Standardized competency assessment enhances quality assurance in medical education.</p>',
    status: 'approved',
    submittedBy: 'user-6',
    submittedAt: '2024-01-24T15:30:00Z',
    reviewedBy: 'reviewer-1',
    reviewedAt: '2024-01-26T10:45:00Z',
  },
]

export const mockComments: { [abstractId: string]: Comment[] } = {
  'abstract-1': [
    {
      id: 'comment-1',
      abstractId: 'abstract-1',
      userId: 'reviewer-1',
      userName: 'Dr. Emily Johnson',
      content: 'This is a very interesting study. Could you provide more details about the methodology used to select the 10 African countries?',
      createdAt: '2024-01-28T14:30:00Z',
    },
    {
      id: 'comment-2',
      abstractId: 'abstract-1',
      userId: 'reviewer-2',
      userName: 'Prof. James Wilson',
      content: 'The 40% improvement is impressive. Have you considered submitting this for an oral presentation?',
      createdAt: '2024-01-29T09:00:00Z',
    },
  ],
  'abstract-2': [
    {
      id: 'comment-3',
      abstractId: 'abstract-2',
      userId: 'reviewer-1',
      userName: 'Dr. Emily Johnson',
      content: 'Excellent work! The AI integration is well-thought-out. Approved for oral presentation.',
      createdAt: '2024-01-29T09:15:00Z',
    },
  ],
  'abstract-3': [
    {
      id: 'comment-4',
      abstractId: 'abstract-3',
      userId: 'reviewer-1',
      userName: 'Dr. Emily Johnson',
      content: 'Please provide more information about the VR equipment used and cost analysis for implementation.',
      createdAt: '2024-01-28T16:30:00Z',
    },
  ],
  'abstract-4': [
    {
      id: 'comment-5',
      abstractId: 'abstract-4',
      userId: 'reviewer-2',
      userName: 'Prof. James Wilson',
      content: 'The methodology section needs more detail. The sample size appears too small for the conclusions drawn.',
      createdAt: '2024-01-27T13:20:00Z',
    },
  ],
  'abstract-5': [],
  'abstract-6': [
    {
      id: 'comment-6',
      abstractId: 'abstract-6',
      userId: 'reviewer-1',
      userName: 'Dr. Emily Johnson',
      content: 'Outstanding research with significant implications for medical education. Strongly recommend for oral presentation.',
      createdAt: '2024-01-26T10:45:00Z',
    },
  ],
}
